apiVersion: apps/v1
kind: Deployment
metadata: 
name: sample-app
spec: 
selector: 
    matchLabels:
    app: sample-app
replicas: 1
template:
    metadata:
    labels: 
        app: sample-app
    spec:
    containers:
    - name: sample-app
        image: saipriyabalu/sample:v1 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
name: sample-app
spec:
selector:
    app: sample-app
ports:
- protocol: "TCP"
    port: 8080
    targetPort: 8080
type: LoadBalancer
