apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
        - name: html-app-container
          image: saipriyabalu/sample:v1
          ports:
            - containerPort: 80
