apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-html-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-html-app
  template:
    metadata:
      labels:
        app: sample-html-app
    spec:
      containers:
        - name: sample-html-app
          image: sample-html-app:v1
          ports:
            - containerPort: 80

